m4_include(`join.m4')m4_dnl
m4_include(`foreach2.m4')m4_dnl
m4_include(`array.m4')m4_dnl
m4_include(`default.m4')m4_dnl
m4_divert(-1)dnl
m4_next_array(`DEVICE')
m4_next_array(`DISK')
m4_next_array(`META')
TMPL_DEFS
m4_divert`'m4_dnl
m4_include(TMPL)m4_dnl
