#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

. ${0%/*}/setup.sh

setup "$@"

on "${NODES[@]}" drbdadm up all
connection_event "${CONNECTIONS[@]}" -y ' connection .* role:Secondary'
on "${NODES[@]}" drbdadm down all
on "${NODES[@]}" rmmod drbd
