#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

. ${0%/*}/setup.sh

setup --disk=10M "$@"

on "${NODES[@]}" drbdadm up all
on "${NODES[0]}" drbdadm primary --force all
event "${NODES[0]}" -y ' resource .* role:Primary'
for node in "${NODES[@]}"; do
    if [ "$node" = "${NODES[0]}" ]; then
	event "$node" -y ' device .* disk:UpToDate'
    else
	event "$node" --timeout=300 -y ' peer-device .* disk:UpToDate'
    fi
done
on "${NODES[@]}" drbdadm down all
on "${NODES[@]}" rmmod drbd
