#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

. ${0%/*}/setup.sh

setup --disk=10M "$@"

on "${NODES[@]}" drbdadm up all
for node in "${NODES[@]}"; do
    event "$node" -y ' device .* disk:Inconsistent'
done

# Use unlimited resync bandwidth
on "${NODES[@]}" drbdadm disk-options --c-min-rate=0 all

on "${NODES[0]}" drbdadm primary --force all
event "${NODES[0]}" -y ' resource .* role:Primary' -y ' device .* disk:UpToDate'
for node in "${NODES[@]}"; do
    if [ "$node" != "${NODES[0]}" ]; then
	event "$node" --timeout=300 -y ' device .* disk:UpToDate'
    fi
done
on "${NODES[@]}" drbdadm down all
on "${NODES[@]}" rmmod drbd
