#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

. ${0%/*}/setup.sh

setup --disk=10M "$@"

on "${NODES[@]}" drbdadm new-resource all
on "${NODES[@]}" drbdadm connect all
# FIXME: It may be interesting to add volume(s) without waiting
# for the connections to be established first.
connection_event "${CONNECTIONS[@]}" -y ' connection .* connection:Connected'
on "${NODES[@]}" drbdadm new-minor all
on "${NODES[@]}" drbdadm attach all

_force_primary
_initial_resync
_down
_rmmod
