#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

. ${0%/*}/setup.sh

exec < /dev/null

setup "$@"
on "${NODES[@]}" drbdadm up all
event "${NODES[@]}" -y connection:Connected
on "${NODES[@]}" drbdadm down all

# FIXME: This test case currently fails to wait until all connections
# are established with more than two nodes (that is, it would have to
# wait for each connection to change into state connection:Connected).
#
# (Also see the TODO file; the event log will contain the sought-for
# string multiple times if a property other than the connection state
# changes!)
