#! /usr/bin/env python3
### vmshed: { "vms_all": [2,3], "drbd_version_min": "9.2" }

from python import drbdtest, endurance

resource = drbdtest.setup_resource(min_nodes=2)

config = endurance.EnduranceConfig()
config.protocol = 'C'

endurance.run_resync(resource, config)
