#! /usr/bin/env python3
### vmshed: { "vms_all": [3,4], "drbd_version_min": "9.2" }

from python import drbdtest, endurance

resource = drbdtest.setup(min_nodes=3)

config = endurance.EnduranceConfig()
config.protocol = 'C'
config.network_rate = '1024mbit'
config.disk_delay_ms = 5
config.diskless_primary = True

endurance.run_resync(resource, config)
