image: $LINBIT_DOCKER_REGISTRY/drbd-tests-build

variables:
  VIRTER_VERSION: v0.5.0
  VMSHED_VERSION: v0.5.0
  BUILD_HELPERS_VERSION: c0d39c0e5a2235262f21d072c4bf3b2dd62b2040

stages:
  - base_image
  - build
  - test
  - publish

base_image:
  stage: base_image
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
  tags:
    - libvirt
  # avoid blocking the pipeline with a manual job
  allow_failure: true
  cache:
    paths:
      - download
  script:
    - |
      mkdir -p download bin
      [ -e download/virter-$VIRTER_VERSION ] || { curl -sSfL https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64 > download/virter-$VIRTER_VERSION && chmod +x download/virter-$VIRTER_VERSION ; }
      [ -e download/rq ] || curl -sSfL https://github.com/dflemstr/rq/releases/download/v1.0.2/rq-v1.0.2-x86_64-unknown-linux-gnu.tar.gz | tar -C download -xvzf -
      ln -s ../download/virter-$VIRTER_VERSION bin/virter
      ln -s ../download/rq bin/rq
      export PATH="$(readlink -f bin):$PATH"
    - |
      cd virter
      virter image rm drbd-base-image
      for image in $(make -s print_base_images); do
        make "base_image_$image" BASE_IMAGE_NAME=drbd-base-image
        virter image save drbd-base-image | curl -isSf -u $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD -H "Tranfer-Encoding: chunked" -F raw.directory=/ -F raw.asset0=@- -F "raw.asset0.filename=$image" "$LINBIT_REGISTRY_URL/service/rest/v1/components?repository=vm-image"
        virter image rm drbd-base-image
      done

bundle:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - make bundle
  artifacts:
    paths:
      - drbd-test-bundle.tgz
    expire_in: 1 week

build-docker:
  stage: build
  tags:
    - shell
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - docker login -u $LINBIT_REGISTRY_USER -p $LINBIT_REGISTRY_PASSWORD $LINBIT_DOCKER_REGISTRY
    - make DOCKER_IMAGE_NAME=$LINBIT_DOCKER_REGISTRY/drbd9-tests:$CI_COMMIT_SHA docker
    - docker push $LINBIT_DOCKER_REGISTRY/drbd9-tests:$CI_COMMIT_SHA

push-docker:
  stage: publish
  tags:
    - shell
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  dependencies:
    - build-docker
  script:
    - docker login -u $LINBIT_REGISTRY_USER -p $LINBIT_REGISTRY_PASSWORD $LINBIT_DOCKER_REGISTRY
    - docker pull $LINBIT_DOCKER_REGISTRY/drbd9-tests:$CI_COMMIT_SHA
    - docker tag $LINBIT_DOCKER_REGISTRY/drbd9-tests:$CI_COMMIT_SHA $LINBIT_DOCKER_REGISTRY/drbd9-tests:latest
    - docker push $LINBIT_DOCKER_REGISTRY/drbd9-tests:latest


publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - curl -isSf -u $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file drbd-test-bundle.tgz $LINBIT_REGISTRY_URL/repository/test-suite/
  dependencies:
    - bundle


test:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - libvirt
  cache:
    paths:
      - download
  script:
    - curl -sSfL -u gitlab-ci-token:$CI_JOB_TOKEN $CI_SERVER_URL/linbit/build-helpers/-/archive/$BUILD_HELPERS_VERSION/ignored.tar.gz | tar -xvzf -
    - mv build-helpers-* build-helpers
    - . build-helpers/gitlab-utils.sh
    - |
      ci_prepare_tools
      ci_fetch_rq
      ci_fetch_binary virter virter-$VIRTER_VERSION https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64
      ci_fetch_binary vmshed vmshed-$VMSHED_VERSION https://github.com/LINBIT/vmshed/releases/download/$VMSHED_VERSION/vmshed-linux-amd64
    - |
      mkdir -p drbd-test-bundle
      tar -C drbd-test-bundle -xvf drbd-test-bundle.tgz
    - docker image pull $LINBIT_DOCKER_REGISTRY/drbd9-tests:$CI_COMMIT_SHA
    - |
      export DRBD_VERSION=9.0.0.latest
      export DRBD_UTILS_VERSION=9.0.0.latest-*
      export DRBD9_TESTS_VERSION=$CI_COMMIT_SHA
      ./drbd-test-bundle/virter/run-test.sh
  dependencies:
    - bundle
    - build-docker
  artifacts:
    # provide a convenient name so that the downloaded artifacts can be identified
    name: $CI_PROJECT_NAME-$CI_JOB_ID
    paths:
      - tests-out/
    when: always
    reports:
      junit: tests-out/test-results/*.xml
