#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

HERE=${0%/*}
. $HERE/lib/setup.sh

setup --min-nodes=1 "$@"

_up
_force_primary
_initial_resync
on ${NODES[0]} drbdadm secondary all

# Switching roles must not cause any more resyncs:
push_forbidden_patterns \
	'replication:.*'

# Note: this test can easily be modified to test auto-promote instead.

for ((i = 0; i < 100; i++)); do
    node=${NODES[RANDOM % ${#NODES[@]}]}
    on $node drbdadm primary all
    event $node -y 'resource .* role:Primary'
    on $node drbdadm secondary all
done

# Note: this test does not define any devices, so disconnecting does not
# require a two-phase commit.  The peer of a disconnecting node will only
# notice a socket close.

pop_forbidden_patterns -f \
	'connection:NetworkFailure' \
	'replication:.*'

_down
_rmmod
