#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

HERE=${0%/*}
. $HERE/lib/setup.sh

setup "$@"

on "${NODES[@]}" drbdadm up all
connection_event "${CONNECTIONS[@]}" -y ' connection .* role:Secondary'
on "${NODES[@]}" drbdadm down all
event "${NODES[@]}" -y 'destroy resource'

on "${NODES[@]}" rmmod drbd
