#! /bin/bash

# Pass this script a list of host names to use as the test nodes.

HERE=${0%/*}
. $HERE/lib/setup.sh

setup --disk=10M "$@"

first_node="${NODES[0]}"
first_volumes=( ${VOLUMES[$first_node]} )
other_nodes=( $(all_nodes_except "$first_node") )
other_volumes=( $(all_volumes_except ${first_volumes[@]}) )

on "$first_node" drbdadm up all
on "$first_node" drbdadm primary --force all
event "$first_node" -y 'resource .* role:Primary'

volume_event "${first_volumes[@]}" -y 'device .* disk:UpToDate'

# Note: this check does NOT wait for the resync to be finished!
# (This was a mistake in the test, but it turned out that aborting
# resyncs causes a BUG -- Objects remaining in drbd_bm on
# kmem_cache_close().)
volume_event "${other_volumes[@]}" --timeout=300 -y 'peer-device .* peer-disk:UpToDate'

on "${NODES[@]}" drbdadm down all
_rmmod
