#! /usr/bin/env python

# Pass this script a host name to use as the test node.

import time

from python import drbdtest
from python.drbdtest import verbose

resource = drbdtest.setup(min_nodes=2, max_nodes=2)
resource.add_disk('4M')

# need the second node only to get a network config etc.
node = resource.nodes[0]
node.up()

# wait for the initialization to be done
node.event(r'connection .* connection:Connecting')

# try del-path; VM must not crash
try:
    node.run(["drbdadm", "del-path", "all", "-v"])
    raise RuntimeError("drbdadm del-path should have returned an error code")
except:
    pass

node.adjust()
try:
    node.run(["drbdadm", "del-peer", "all", "-v"])
    raise RuntimeError("drbdadm del-peer should have returned an error code")
except:
    pass

# verify that the VM is still running by requesting some action
# and waiting for it to happen.
node.primary(force=True, wait=True)
