#! /usr/bin/env python

# Pass this script a host name to use as the test node.

import subprocess

from python import drbdtest
from python.drbdtest import verbose

resource = drbdtest.setup(min_nodes=2, max_nodes=2)
resource.add_disk('4M')

# need the second node only to get a network config etc.
node = resource.nodes[0]
node.up()

# wait for the initialization to be done
node.event(r'connection .* connection:Connecting')

# run these commands again; VM must not crash.
# drbdadm is expected to report an error.
try:
    node.run(["drbdadm", "new-path", "all", "-v"])
    raise RuntimeError("drbdadm new-path should have returned an error code")
except subprocess.CalledProcessError:
    pass

try:
    node.run(["drbdadm", "new-peer", "all", "-v"])
    raise RuntimeError("drbdadm new-peer should have returned an error code")
except subprocess.CalledProcessError:
    pass

# verify that the VM is still running by requesting some action
# and waiting for it to happen.
node.primary(force=True, wait=True)
