#! /usr/bin/env python3
### vmshed: { "vms_all": [3], "vms_ci": null, "drbd_version_min": "9.0" }

# Test concurrent attach on two secondaries. With resync and without resync
# This test failed up to (including) 9.0.27

from python import drbdtest
from python.drbdtest import connections, log, peer_devices

resource = drbdtest.setup(nodes=3)
resource.add_disk('10M')
resource.up_wait()

primary_n = resource.nodes[0]
secondaries = resource.nodes[1:]

log('* Make up-to-date data available.')
resource.skip_initial_sync()

primary_n.primary()

log('* detach/attach no writes in between.')
secondaries.detach()
secondaries.attach()
secondaries.volumes.event(r'device .* disk:UpToDate')

log('* detach/attach with write in between.')
secondaries.detach()
primary_n.volumes.write(direct=1)
secondaries.attach()
secondaries.volumes.event(r'device .* disk:UpToDate')

resource.down()
resource.teardown()
