#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": null, "drbd_version_min": "9.2", "variants_add": ["zfs"]}
#
# This test shows that the implementation of `suspend-io` (as of
# drbd-9.2.13) does not guarantee that the in-flight I/O is settled
# before the command returns.
# Thus, snapshots taken between `drbdsetup suspend-io` are not
# guaranteed to have the same contents between the nodes.
#

import time
from python import drbdtest
from python.drbdtest import connections, log, peer_devices
from python import busywrite
from python import datatools

resource = drbdtest.setup_resource(nodes=2)
resource.net_options = 'ping-timeout 30;'
node_a, node_b = resource.nodes

resource.add_disk('35M')
resource.up_wait()

log('* Make up-to-date data available.')
resource.skip_initial_sync()

node_a.primary()

writer = busywrite.BusyWrite(node_a.volumes[0])
writer.start('--size=30M --numjobs=2')
time.sleep(0.7)
connections(node_a, node_b).block(lead_seconds=0.3, for_seconds=1)
node_a.drbdadm(['suspend-io', resource.name])
node_a.event(r'resource .* suspended:user')
snapshot_path = node_a.volumes[0].snapshot('32M')
snapshot_path = node_b.volumes[0].snapshot('32M')
node_a.drbdadm(['resume-io', resource.name])
node_a.event(r'resource .* suspended:')
writer.stop()

md5sums = []
for n in resource.nodes:
    md5sums.append(datatools.read_md5sum(n, snapshot_path, 30))

if len(set(md5sums)) > 1:
    log(md5sums)
    raise RuntimeError("Data differs!")

log('* Shut down and clean up.')
resource.down()
resource.cluster.teardown()
