#! /usr/bin/env python3
### vmshed: { "vms_all": [3], "vms_ci": [3], "drbd_version_min": "9.0" }
#
# This test configures a 3 node system, with one node (A) diskless.
# One node (C) is isolated, node A promotes and demotes 2 times. Then
# ensure the isolated node can be re-integrated with C.

import time
from python import drbdtest
from python.drbdtest import connections, log, peer_devices

def do_test(node_a, node_b, node_c, connect_to_diskless_first=False):
    def connect_ca():
        connection_ca = connections(node_c, node_a)
        connection_ca.connect()
        pd = peer_devices(node_c, node_a)
        pd.event(r'peer-device .* replication:Established')

    def new_current_uuid_a():
        node_a.primary()
        time.sleep(0.2)
        node_a.write(direct=1)
        time.sleep(0.2)
        node_a.secondary()
        time.sleep(0.2)

    log('* Isolating %s' % (node_c.name))
    connection_cb = connections(node_c, node_b)
    connection_ca = connections(node_c, node_a)
    connection_cb.disconnect()

    log('* Promoting multiple times on %s' % (node_a.name))
    new_current_uuid_a()
    connection_ca.disconnect()
    new_current_uuid_a()
    new_current_uuid_a()

    if connect_to_diskless_first:
        connect_ca()

    log('* Resync from %s to %s' % (node_b.name, node_c.name))
    connection_cb.connect()

    pd = peer_devices(node_c, node_b)
    pd.event(r'peer-device .* replication:SyncTarget')
    pd.event(r'peer-device .* replication:Established')

    if not connect_to_diskless_first:
        connect_ca()

    return

resource = drbdtest.setup_resource(nodes=3)
node_a, node_b, node_c = resource.nodes
diskful_nodes = resource.nodes.difference([node_a])
resource.add_disk('10M', diskful_nodes=diskful_nodes)

resource.up_wait()

log('* Make up-to-date data available.')
resource.skip_initial_sync()

do_test(node_a, node_b, node_c, connect_to_diskless_first=True)
do_test(node_a, node_b, node_c, connect_to_diskless_first=False)

log('* Shut down and clean up.')
resource.down()
resource.cluster.teardown()
