#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": null, "drbd_version_min": "9.2", "networks": [{"dhcp": true}] }

from python import drbdtest
from python.drbdtest import connections, log, peer_devices
from python import datatools
from python import trafficcontrol

resource = drbdtest.setup_resource(nodes=2, multi_paths=True)
primary_n, secondary_n = resource.nodes

resource.add_disk('150M')
resource.net_options = 'load-balance-paths yes;'

resource.up_wait()

primary_tc = trafficcontrol.TrafficControl(primary_n, resource.nodes)
primary_tc.slow_down(secondary_n, speed='30MiBps')

log('* Run initial sync with timeout that is only achievable using both paths')
primary_n.primary(force=True)
resource.initial_resync(timeout=4)

log('* Do some writes')
primary_n.write(size='90M', bs='16K', direct=1, ioengine='libaio', iodepth=4)
primary_n.secondary()

primary_tc.reset()

log('* Shut down and clean up.')
resource.down()
datatools.verify_data(resource.nodes, size_mb=140, backing_disk=True)
resource.cluster.teardown()
