#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": [2] }

# Pass this script a list of host names to use as the test nodes.

from python import drbdtest
from python.drbdtest import log

resource = drbdtest.setup(max_nodes=2)
first_node = resource.nodes[0]
other_node = resource.nodes.difference([first_node])

resource.add_disk('10M')

log('* Bring up the first node, make it primary, and write defined data onto all volumes.')
resource.up_wait()
resource.skip_initial_sync()

dev_name = '/dev/drbd%d' % first_node.disks[0].minor
first_node.run([drbdtest.helper('misaligned_bio.py'), dev_name, 'write'])
first_node.run([drbdtest.helper('misaligned_bio.py'), dev_name, 'verify'])
other_node.run([drbdtest.helper('misaligned_bio.py'), dev_name, 'verify'])

# That is BLKZEROOUT, BLKDISCARD and BLKSECDISCARD
first_node.run([drbdtest.helper('unusual_bios.py'), dev_name])

log('* Shut down and clean up.')
resource.down()
# An assertion sometimes fails when running this test. Disable validation until
# the issue is fixed in DRBD.
resource.teardown(validate_dmesg=False)
