#! /usr/bin/env python

# Pass this script a list of host names to use as the test nodes.

from python import drbdtest2
from python.drbdtest2 import verbose

resource = drbdtest2.setup(nodes=2)
first_node = resource.nodes[0]
other_node = resource.nodes.difference([first_node])

resource.add_disk('10M')

verbose('* Bring up the first node, make it primary, and write defined data onto all volumes.')
resource.up_wait()
resource.skip_initial_sync()

dev_name = '/dev/drbd%d' % first_node.disks[0].minor
first_node.run(['misaligned_bio.py', dev_name, 'write'])
first_node.run(['misaligned_bio.py', dev_name, 'verify'])
other_node.run(['misaligned_bio.py', dev_name, 'verify'])

verbose('* Shut down and clean up.')
try:
    resource.down()
except:
    pass
resource.rmmod()
