#! /usr/bin/env python

# Pass this script a list of host names to use as the test nodes.

from python import drbdtest
from python.drbdtest import verbose

resource = drbdtest.setup(max_nodes=2)
first_node = resource.nodes[0]
other_node = resource.nodes.difference([first_node])

resource.add_disk('10M')

verbose('* Bring up the first node, make it primary, and write defined data onto all volumes.')
first_node.up()
first_node.primary(force=True)

verbose('* Make the first node secondary again to allow read access on the other nodes.')
first_node.secondary()

verbose('* Bring up all other nodes as well, wait until they have all the data, and verify the data received.')
other_node.up()
resource.initial_resync(first_node)
dev_name = '/dev/drbd%d' % first_node.disks[0].minor
first_node.run(['missaligned_bio.py', dev_name, 'write'])
first_node.run(['missaligned_bio.py', dev_name, 'verify'])
other_node.run(['missaligned_bio.py', dev_name, 'verify'])

verbose('* Shut down and clean up.')
resource.down()
resource.rmmod()
