#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": null, "drbd_version_min": "9.2", "networks": [{"dhcp": true}] }
# Performs basic set up from inside a network namespace and tests that a connection is established
from python import drbdtest

resource = drbdtest.setup(nodes=2, netns='drbdtest')
resource.nodes.up_wait()
resource.connections.event(r'connection .* connection:Connected')

resource.down()
resource.teardown()
