#! /usr/bin/env python3
### vmshed: { "vms_all": [3, 5], "vms_ci": [3], "drbd_version_min": "9.0" }

# Pass this script a list of host names to use as the test nodes.

from python import drbdtest
from python.drbdtest import connections, log, peer_devices
from subprocess import CalledProcessError

resource = drbdtest.setup(min_nodes=3, max_nodes=5)

resource.add_disk('10M')
resource.net_options = 'ping-int 1;'
resource.up_wait()

log('* Make up-to-date data available.')
resource.skip_initial_sync();

def write_on_node(node):
    node.volumes.write(end_fsync=1)

def wait_backward_propagating_resyncs(nodes):
    for i in range(len(nodes) - 1, 0):
        rspd = peer_devices(nodes[i], nodes[i-1])
        rtpd = peer_devices(nodes[i-1], nodes[i])
        rspd.event(r'peer-device .* replication:SyncSource')
        rspd.event(r'peer-device .* replication:Established')
        rtpd.event(r'peer-device .* replication:SyncTarget')
        rtpd.event(r'peer-device .* replication:Established')

def outdate_test(write_between_actions = False):
    first_node = resource.nodes[0]
    last_node = resource.nodes[-1]
    log("* Make a node primary and see if volumes on weak nodes become Outdated.")
    first_node.primary()
    weak_nodes = resource.nodes.difference(resource.nodes[0:2])
    weak_nodes.volumes.event(r'device .* disk:Outdated')
    if write_between_actions:
        write_on_node(first_node)

    log("* See if node becomes UpToDate when connecting to the primary.")
    cs = drbdtest.Connections()
    cs.bidir_add(first_node, last_node)
    cs.connect()
    cs.event(r'connection .* connection:Connected')

    pds = drbdtest.PeerDevices()
    pds.extend(peer_devices(first_node, last_node))
    last_node.volumes[0].event(r'device .* disk:UpToDate')
    pds.event(r'peer-device .* peer-disk:UpToDate')

    log("* See if node becomes Outdated when connection to primary is lost.")
    resource.forbidden_patterns.remove(r'connection:NetworkFailure')
    resource.forbidden_patterns.remove(r'connection:Timeout')

    first_node.block_path(last_node, 0)
    cs.event(r'connection .* connection:(NetworkFailure|Timeout)')
    last_node.volumes[0].event(r'device .* disk:Outdated')
    if write_between_actions:
        write_on_node(first_node)
        wait_backward_propagating_resyncs(weak_nodes)

    first_node.unblock_path(last_node, 0)
    last_node.volumes[0].event(r'device .* disk:UpToDate')
    pds.event(r'peer-device .* peer-disk:UpToDate')

    resource.forbidden_patterns.add(r'connection:NetworkFailure')
    resource.forbidden_patterns.add(r'connection:Timeout')

    log("* See if node becomes Outdated when disconnecting from the primary.")
    first_to_last = drbdtest.Connections()
    first_to_last.extend(connections(first_node, last_node))
    first_to_last.disconnect(wait=False)
    last_node.volumes[0].event(r'device .* disk:Outdated')
    if write_between_actions:
        write_on_node(first_node)
        wait_backward_propagating_resyncs(weak_nodes)

    first_to_last.connect()
    last_node.volumes[0].event(r'device .* disk:UpToDate')
    pds.event(r'peer-device .* peer-disk:UpToDate')

    last_to_first = drbdtest.Connections()
    last_to_first.extend(connections(last_node, first_node))
    last_to_first.disconnect(wait=False)
    last_node.volumes[0].event(r'device .* disk:Outdated')
    if write_between_actions:
        write_on_node(first_node)
        wait_backward_propagating_resyncs(weak_nodes)

    last_to_first.connect()
    last_node.volumes[0].event(r'device .* disk:UpToDate')
    pds.event(r'peer-device .* peer-disk:UpToDate')

    first_to_last.disconnect(wait=False)
    last_to_first.disconnect(wait=False)
    last_node.volumes[0].event(r'device .* disk:Outdated')
    if write_between_actions:
        write_on_node(first_node)
        wait_backward_propagating_resyncs(weak_nodes)

    log("* Turn primary into secondary and see if previously weak nodes become UpToDate.")
    first_node.secondary()
    weak_nodes.difference([last_node]).volumes.event(r'device .* disk:UpToDate')


log('* Forming a chain of nodes.')
chain = drbdtest.Connections()
for i in range(0, len(resource.nodes) - 1):
    chain.bidir_add(resource.nodes[i], resource.nodes[i+1])

resource.connections.difference(chain).disconnect()

outdate_test()
outdate_test(write_between_actions=True)

try:
    resource.nodes[0].run(['sleep', '0.5'])
    resource.nodes[0].run(['udevadm', 'settle', '--timeout=2'])
except:
    pass

log('* Shut down and clean up.')
resource.down()
resource.teardown()
