#! /usr/bin/env python3
### vmshed: { "vms_all": [3], "vms_ci": null, "drbd_version_min": "9.0" }

# This test mimics the way drbdmanage uses DRBD:
#  * use drbdmeta to explicit set the current-UUID
#  * set the data as consistent an up-to-date
#  * Have one diskless node, that becomes primary
#  * One of the servers joins later
#
# Note the server that joins late has node-id 0, that is by intention,
# and is necessary to tigger an issue I was hunting at the time I wrote
# the test.


# TO FIX IN DRBD:
# * This test right now shows that the bitmap does not get initialized, and that
#   the two servers consider the random garbage as bitmap between the two.
#   TODO: Assert in the test that out-of-sync is 0
# * Consider if the new UUID should be created immediately when the 3rd machine
#   joins

import time
from python import drbdtest
from python.drbdtest import MetadataFlag, connections, log, peer_devices
from subprocess import CalledProcessError

resource = drbdtest.setup(nodes=3)

diskful_nodes = resource.nodes[:2]
resource.add_disk('10M', diskful_nodes=diskful_nodes)

diskless_node = resource.nodes.diskless[0]

def pre_existing_test(write_between_actions = False):
    log('* Pretending both servers have up-to-date data.')
    for n in diskful_nodes:
        n.run(["/bin/bash", "-c",
               "dd if=/dev/urandom of=%s seek=2000 bs=4096 || true" % (n.disks[0].disk)])
        # Preset the bitmap to some randomly set bits...

        n.volumes[0].create_md()
        n.set_gi(n.volumes[0], '87236C45CB784220',
                flags_set=MetadataFlag.CONSISTENT | MetadataFlag.WAS_UP_TO_DATE)

    log('* Bringing up the diskless and one server, connect them')
    resource.nodes.diskful[1].up()
    diskless_node.up()
    cs = connections(diskless_node, resource.nodes.diskful[1], bidir=True)
    cs.event(r'connection .* connection:Connected')
    pds = peer_devices(diskless_node, resource.nodes.diskful[1])
    pds.event(r'peer-device .* peer-disk:UpToDate')

    log('* Promoting the diskless')
    diskless_node.primary()
    if write_between_actions:
        diskless_node.volumes.write(end_fsync=1)

    log('* Connect the remaining server to the server that is already up')
    n = resource.nodes.diskful[0]
    n.new_resource()
    n.new_minor()
    n.new_peer()
    n.new_path()
    n.drbdadm(["peer-device-options", "all"])
    n.attach()
    cs = connections(n, resource.nodes.diskful[1])
    cs.connect()
    cs.event(r'connection .* connection:Connected')

    log('* Asserting that it goes Outdated now')
    n.volumes[0].event(r'device .* disk:Outdated')

    # Ensure nothing is out of sync!
    pds = peer_devices(n, resource.nodes.diskful[1])
    if not write_between_actions:
        resource.forbidden_patterns.update([r'out-of-sync:[1-9][0-9]*'])
    pds.event(r'peer-device .* replication:Established')
    if not write_between_actions:
        resource.forbidden_patterns.difference_update([r'out-of-sync:[1-9][0-9]*'])

    diskless_node.secondary()
    cs = connections(resource.nodes.diskful[1], diskless_node)
    cs.event(r'connection .* role:Secondary')

    log('* Shut down and clean up.')
    resource.down()

pre_existing_test(write_between_actions = True)
pre_existing_test(write_between_actions = False)

resource.teardown()
