#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": [2], "drbd_version_min": "8.4" }
#
# Promote while we hole the uuid_sem . There was a locking bug
# in the code that caused this to deadlock. Keep such a test
# in the testsuite so that we see it quickly when we re-introduce
# it.

from python import drbdtest
from python.drbdtest import connections, log, peer_devices
from python import busywrite
import time
#import os

def my_log(str):
    log(str)
    for node in resource.nodes:
        node.run(["echo", str])

resource = drbdtest.setup_resource(nodes=2)
resource.add_disk('10M')
resource.up_wait()

A = resource.nodes[0]
B = resource.nodes[1]
a_b = connections(A)
b_a = connections(B)
pds = drbdtest.PeerDevices.from_connections(resource.connections)

my_log('* Make up-to-date data available.')
resource.skip_initial_sync()

my_log('* Start by disconnect.')
a_b.disconnect()
b_a.event(r'connection:Connecting')

A.block_packet_type(drbdtest.P_SIZES, from_node=B)
A.primary()
a_b.connect()
time.sleep(0.8)
my_log('* Creating new UUID while uuid_sem is locked.')
writer = busywrite.BusyWrite(A.volumes[0])
writer.start(fio_base_args='--rw=write --size=4k --direct=1')
A.unblock_packet_type(drbdtest.P_SIZES, from_node=B)

pds.event(r'peer-device .* replication:Established')

log('* Wait for background fio process to finish')
writer.wait()

log('* Shut down and clean up.')

resource.down()
resource.cluster.teardown()
