#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": [2], "drbd_version_min": "9.0" }

# Pass this script a host name to use as the test node.

from python import drbdtest
from python.drbdtest import connections, log, peer_devices
import re
import time


def get_ref_counts(lines, which):
    res = {}
    for l in lines:
        for name in list(which.keys()):
            m = re.search(r'^' + name + r'\s+\d+\s+(-?\d+)', l)
            if m:
                res[name] = int(m.group(1))
    return res

def ref_count(node, compare):
    rc = {}
    for s in range(0, 3000, 500):
        lines = node.run(['lsmod'], return_stdout=True, update_config=False).split('\n')
        rc = get_ref_counts(lines, compare)
        if compare == rc:
            break;
        time.sleep(0.5) # some refs are dropped after RCU grace periods. Wait up to 3 seconds
    log(('expect %s, found %s' % (compare, rc)))
    if compare != rc:
        raise Exception('On "%s" wanted %s, got %s!' % (node, compare, rc))

def expect_drbd(node, drbd, transport):
    transport_module = 'drbd_transport_tcp'
    if resource.transport:
        transport_module = 'drbd_transport_{}'.format(resource.transport.replace('-','_'))
    ref_count(node, {'drbd': drbd, transport_module: transport})

def loaded_transports(node):
    lines = node.run(['lsmod'], return_stdout=True, update_config=False).split('\n')
    transports = 0
    for l in lines:
        m = re.match(r'^drbd_transport_', l)
        if m:
            transports += 1
    return transports

resource = drbdtest.setup_resource(nodes=2)
resource.up_wait()

transports = loaded_transports(resource.nodes[0])

node = resource.nodes[0]
other = resource.nodes[1]

node.primary(force=True)

expect_drbd(node, 1 + transports, 1)

# disconnect doesn't remove the "connection"
node.disconnect(other)
expect_drbd(node, 1 + transports, 1)

# neither does this
# TODO: get connection info from testsuite
# node.run(['drbdsetup', 'del-path', resource, 1, c, c])
# expect_drbd(node, 2, 1)

# but this should
node.run(['drbdsetup', 'del-peer', resource.name, '1'])
expect_drbd(node, 1 + transports, 0)

# get up again
# node.connect(other) # doesn't work, drbdadm doesn't recreate the connection data in the kernel
node.drbdadm(['adjust', resource.name])
expect_drbd(node, 1 + transports, 1)

# actually use it
node.volumes.fio(drbdtest.fio_write_args)
expect_drbd(node, 1 + transports, 1)

# change a setting
node.run(['drbdsetup', 'net-options', resource.name, '1', '--verify-alg=md5'])
expect_drbd(node, 1 + transports, 1)

# change some settings, badly; ignore error
try:
    node.run(['drbdsetup', 'net-options', resource.name, '1', '--verify-alg=quaxi-wurstli'])
except:
    pass
expect_drbd(node, 1 + transports, 1)

# Now "up" with wrong data
node.down()
expect_drbd(node, transports, 0)
resource.net_options = 'verify-alg quaxi-wurstly;'
try:
    node.up()
except:
    pass
# No reference taken, because no valid config
expect_drbd(node, 1 + transports, 0)


resource.net_options = 'verify-alg md5;';
node.drbdadm(['adjust', resource.name])
expect_drbd(node, 1 + transports, 1)


resource.down()
# the transport still has a reference...
expect_drbd(node, transports, 0)


resource.cluster.teardown()
