#! /usr/bin/env python3
### vmshed: { "vms_all": [1], "vms_ci": [1], "drbd_version_min": "9.0" }

from python import drbdtest

resource = drbdtest.setup_resource(nodes=1)
node = resource.nodes[0]
resource.up_wait()

orig_name = resource.name

# try to rename the resource
resource.rename('xyz')

# and again, to check that it recognizes the new name
resource.rename('abc')

# and once more, to check that other commands recognize it too
node.primary(wait=False)
node.event(r'change resource name:abc role:Primary')

resource.down()
resource.cluster.teardown()
