#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": null, "vms_rdma_ci": null, "drbd_version_min": "9.2" }

# Test that a missed end-of-resync with 0 dirty bits does not trigger an
# unnecessary resync. With proto >= 124, drbd_uuid_detect_finished_resyncs()
# skips the RS_SOURCE_MISSED_END / RS_PEER_MISSED_END flags when there are
# 0 bits to sync, so both sides go straight to Established.
#
# This tests demonstrates that DRBD had a bug until (including) 9.2.16
# leading to a failed state change within a two-phase-commit

from python import drbdtest
from python.drbdtest import connections, log, peer_devices

resource = drbdtest.setup_resource(nodes=2)
resource.disk_options = 'c-max-rate 1M;'
resource.add_disk('10M')
resource.up_wait()

resource.forbidden_patterns.difference_update([
    r'connection:NetworkFailure',
    r'connection:BrokenPipe'
])

log('* Make up-to-date data available.')
resource.skip_initial_sync()

source_n, target_n = resource.nodes
forward_c = connections(source_n, target_n)
backward_c = connections(target_n, source_n)
forward_pd = peer_devices(source_n, target_n)
backward_pd = peer_devices(target_n, source_n)

log('* Create a resync and block the final UUID exchange.')
forward_c.disconnect()
source_n.volumes[0].write(size='8M', bs='1M', direct=1)
forward_c.connect()

forward_pd.event(r'peer-device .* replication:SyncSource')
backward_pd.event(r'peer-device .* replication:SyncTarget')
source_n.block_packet_type(drbdtest.P_UUIDS110, from_node=target_n)
resource.disk_options = 'c-max-rate 5M;'
resource.nodes.update_config()
target_n.adjust()
backward_pd.event(r'peer-device .* replication:Established')
backward_c.disconnect(force=True)
forward_c.event(r'connection .* connection:Unconnected')
source_n.unblock_packet_type(drbdtest.P_UUIDS110, from_node=target_n)

forward_c.disconnect()

log('* Making the target node Primary and outdating the source, creating the issue')

source_n.run(['drbdsetup', 'outdate', source_n.disks[0].minor])
target_n.primary()

log('* Verify both sides reach Established.')
forward_c.connect()
backward_c.connect()
source_n.event(r'device .* disk:UpToDate', timeout=5)
forward_pd.event(r'peer-device .* replication:Established')
backward_pd.event(r'peer-device .* replication:Established')

log('* Clean up.')
resource.down()
resource.cluster.teardown()
