#! /usr/bin/env python3

# Pass this script a list of host names to use as the test nodes.

from python import drbdtest
from python.drbdtest import log

resource = drbdtest.setup(max_nodes=5)
first_node = resource.nodes[0]
other_nodes = resource.nodes.difference([first_node])

resource.add_disk('10M')

log('* Bring up the first node, make it primary, and write defined data onto all volumes.')
first_node.up_wait()
first_node.primary(force=True)
first_node.volumes.fio(section='write')

log('* Make the first node secondary again to allow read access on the other nodes.')
first_node.secondary()

log('* Bring up all other nodes as well, wait until they have all the data, and verify the data received.')
other_nodes.up()
resource.initial_resync(first_node)
for node in other_nodes:
    node.primary()
    node.volumes.diskful.fio(section='verify')
    node.secondary()

log('* Shut down and clean up.')
resource.down()
resource.rmmod()
