#! /usr/bin/env python3
### vmshed: { "vms_all": [3], "vms_ci": [3], "drbd_version_min": "9.0" }

# This test creates three different versions of the data.
# Then resyncs upstream (that is, between the nodes with the newer data).
# Then resyncs downstream.

from python import drbdtest
from python.drbdtest import connections, log, peer_devices

def connect_and_check(n1, n2):
    cs = connections(n1, n2, bidir=True)
    cs.connect()
    cs.event(r'connection .* connection:Connected')

def wait_sync(node_source, node_target):
    pd_source = peer_devices(node_source, node_target)
    pd_target = peer_devices(node_target, node_source)

    pd_source.event(r'peer-device .* replication:SyncSource')
    pd_source.event(r'peer-device .* replication:Established')
    pd_target.event(r'peer-device .* replication:SyncTarget')
    pd_target.event(r'peer-device .* replication:Established')


# main
resource = drbdtest.setup_resource(nodes=3)
resource.add_disk('10M')
resource.resource_options = 'quorum majority; on-no-quorum io-error;'
resource.up_wait()

log('* Make up-to-date data available.')
resource.skip_initial_sync()

node_a = resource.nodes[0]
node_b = resource.nodes[1]
node_c = resource.nodes[2]

log('* Run test')
node_a.primary()

log('* Disconnect and write something so that the initial UUID is no longer current')
connections(node_c).disconnect()
node_a.write(size='1M', bs='1M', offset='1M', end_fsync=1)
connections(node_c, node_a).connect()
wait_sync(node_a, node_c)

connections(node_c, node_a).disconnect()
node_a.write(size='1M', bs='1M', end_fsync=1)

connections(node_b).disconnect()
node_a.write(size='1M', bs='1M', offset='1M', end_fsync=1)

connections(node_a).disconnect()

log('* Start upstream resync.')
connect_and_check(node_a, node_b)

wait_sync(node_a, node_b)

log('* Start downstream resync after upstream resync finished')
connect_and_check(node_b, node_c)

wait_sync(node_b, node_c)

connect_and_check(node_a, node_c)

log('* Shut down and clean up.')
resource.down()
resource.cluster.teardown()
