#! /usr/bin/env python3
### vmshed: { "vms_all": [3], "vms_ci": [3], "drbd_version_min": "9.0" }
#
# This test configures a 3 node system, isolates one node (A), writes something
# on the remaining partition (B & C). Let the isolated node resync with one of
# the nodes having the new data (B). Then, make it primary while it is sync
# target. Wait until resync finishes, connect it to the other node (C)
# from the "new data partition".

from python import drbdtest
from python.drbdtest import connections, log, peer_devices

resource = drbdtest.setup(nodes=3)
resource.disk_options = 'c-max-rate 1M;'
resource.add_disk('10M')
resource.up_wait()

log('* Make up-to-date data available.')
resource.skip_initial_sync()

[node_a, node_b, node_c] = resource.nodes

log('* Isolating %s' % (node_a.name))
connections(node_a).disconnect()

log('* New data on %s %s' % (node_b.name, node_c.name))
node_b.volumes.write(size='9M', bs='1M')

log('* Resync from %s to %s' % (node_b.name, node_a.name))
connection_ab = drbdtest.Connection(node_a, node_b)
connection_ab.connect()

peer_device_ab = drbdtest.PeerDevice(connection_ab, resource.volumes[0])
while True:
    done = peer_device_ab.event(r'peer-device .* done:([0-9.]+)')
    if float(done[0][0]) > 20.0:
        break

log('* Become primary on %s' % (node_a.name))
node_a.primary()
peer_device_ab.peer_device_options("--c-max-rate=60M")
node_a.volumes.write()

node_a.volumes[0].event(r'device .* disk:UpToDate')

connection_ac = drbdtest.Connection(node_a, node_c)
connection_ac.connect()

log('* Ensure resync from %s to %s' % (node_a.name, node_c.name))
connection_ca = drbdtest.Connection(node_c, node_a)
connection_ca.event(r'connection .* connection:Connected')
connection_ac.event(r'connection .* connection:Connected')
peer_device_ca = drbdtest.PeerDevice(connection_ca, resource.volumes[0])
[[repl_state]] = peer_device_ca.event(r'peer-device .* replication:([^ ]+)')
if repl_state != 'WFBitMapT':
    raise RuntimeError("Expected a resync here but got %s" % (repl_state))

peer_device_ca.peer_device_options("--c-max-rate=60M")
peer_device_ca.event(r'peer-device .* replication:Established')

log('* Shut down and clean up.')
resource.down()
resource.teardown()
