#! /usr/bin/env python3
### vmshed: { "vms_all": [2], "vms_ci": null, "drbd_version_min": "9.2" }

# Before DRBD-9.1.8 drbd issued a discard request for every rs-discard-granularity
# sized block. Ensure it issues only one for every 128MiByte of storage.

# From Documentation/block/stat.txt:
#  0 read I/Os       requests      number of read I/Os processed
#  1 read merges     requests      number of read I/Os merged with in-queue I/O
#  2 read sectors    sectors       number of sectors read
#  3 read ticks      milliseconds  total wait time for read requests
#  4 write I/Os      requests      number of write I/Os processed
#  5 write merges    requests      number of write I/Os merged with in-queue I/O
#  6 write sectors   sectors       number of sectors written
#  7 write ticks     milliseconds  total wait time for write requests
#  8 in_flight       requests      number of I/Os currently in flight
#  9 io_ticks        milliseconds  total time this block device has been active
# 10 time_in_queue   milliseconds  total wait time for all requests
# 11 discard I/Os    requests      number of discard I/Os processed
# 12 discard merges  requests      number of discard I/Os merged with in-queue I/O
# 13 discard sectors sectors       number of sectors discarded
# 14 discard ticks   milliseconds  total wait time for discard requests

import os
from python import drbdtest
from python.drbdtest import log

def number_of_discards(node, vol):
    bd_path = node.run(['readlink', vol.disk], return_stdout=True)
    bd_name = os.path.basename(bd_path)
    stat_content = node.run(['cat', '/sys/block/' + bd_name + '/stat'], return_stdout=True)
    return int(stat_content.split()[11])

resource = drbdtest.setup(nodes=2)
resource.disk_options = 'discard-zeroes-if-aligned yes; rs-discard-granularity 65536; c-max-rate 500M;'
resource.add_disk('1G', thin=True)

node_a, node_b = resource.nodes
dev_name = node_a.volumes[0].device()

node_a.up_wait()
node_a.primary(force=True)
node_a.secondary()

node_b.up_wait()

connection_ba = resource.connections.from_node(node_b).to_node(node_a)
peer_devices_ba = drbdtest.PeerDevices.from_connections(connection_ba)
peer_devices_ba.event(r'peer-device .* replication:SyncTarget')
peer_devices_ba.event(r'peer-device .* replication:Established')

nr_discards = number_of_discards(node_b, node_b.volumes[0])

# 1GiB backend / 128MiB per discard -> 8 discard requests.
if nr_discards > 8:
    raise Exception('More discards than expected nr_discards = {}'
                    .format(nr_discards))

log('* Shut down and clean up.')
resource.down()
resource.teardown()
