#! /usr/bin/env python3
### vmshed: { "vms_all": [2, 5], "vms_ci": [2], "drbd_version_min": "9.0" }

# This test stresses the ability to resolve conflicting two-phase-commits

from python import drbdtest
from python.drbdtest import log
from subprocess import CalledProcessError

resource = drbdtest.setup(min_nodes=2, max_nodes=5)
resource.resource_options = 'twopc-timeout 600;'
resource.net_options = 'socket-check-timeout 5;'
resource.add_disk('4M')

resource.forbidden_patterns.difference_update([
        r'connection:NetworkFailure',
        r'connection:BrokenPipe',
        r'connection:ProtocolError'
    ])

for i in range(20):
    resource.forbidden_patterns.difference_update([
        r'connection:NetworkFailure',
        r'connection:BrokenPipe',
        r'connection:ProtocolError'
    ])

    resource.up_wait()
    resource.forbidden_patterns.difference_update([
        r'connection:NetworkFailure',
        r'connection:BrokenPipe',
        r'connection:ProtocolError'
    ])

    resource.down(concurrent=True)
    resource.forbidden_patterns.difference_update([
        r'connection:NetworkFailure',
        r'connection:BrokenPipe',
        r'connection:ProtocolError'
    ])

resource.teardown()
