#! /usr/bin/env python

# This test stresses the ability to resolve conflicting two-phase-commits

from python import drbdtest
from python.drbdtest import verbose
from subprocess import CalledProcessError

resource = drbdtest.setup(min_nodes=2, max_nodes=5)
resource.resource_options = 'twopc-timeout 600;'
resource.add_disk('4M')

for i in range(20):
    resource.up_wait()
    resource.down(concurrent=True)
