#! /usr/bin/env python3
### vmshed: { "vms_all": [3], "vms_ci": null, "drbd_version_min": "9.1" }

# This test provokes the concurrent two-phase commit for establishing
# the connections from node_a to node_c and node_a to node_b. At first,
# the two-pc a-c starts. Then node_c aborts it and allows a-b to
# overtake.
#
# Up to drbd-9.1.22 and 9.2.11, this results in node_c having a resync
# started and node_a having the connection established (without resync).

from python import drbdtest
from python.drbdtest import MetadataFlag, connections, log, peer_devices
import time

resource = drbdtest.setup_resource(nodes=3)
resource.cluster.create_storage_pool(thin=True)
resource.net_options = 'rr-conflict retry-connect;'
resource.add_disk('100G')
resource.up_wait()

log('* Make up-to-date data available.')
resource.skip_initial_sync()

node_a, node_b, node_c = resource.nodes
connections(node_a, to_nodes=[node_b, node_c]).disconnect()

# Prepare node_c to become a resync Target by giving it the 0x4 cur UUID.
node_c.down()
node_c.set_gi(node_a.volumes[0], '4', flags_set=MetadataFlag.CONSISTENT | MetadataFlag.WAS_UP_TO_DATE)
node_c.up_unconnected()

# Prepare node_c to abort the connect two-pc by making it primary
# and setting rr-conflict=retry-connect.
node_c.primary()

connections(node_c, node_a).connect()
connections(node_b, node_a).event(r'connection .* connection:Connecting')

# Suspend I/O to slowdown meta-data write, delaying state changes
node_a.volumes.suspend()
connections(node_a, node_c).connect(wait=False)
connections(node_a, node_b).connect()
time.sleep(3)
node_a.volumes.resume()

node_c.secondary()
evs = peer_devices(node_a, node_c).event(r'peer-device .* replication:(\S+)')
evt = peer_devices(node_c, node_a).event(r'peer-device .* replication:(\S+)')
drbdtest.ensure('WFBitMapS', evs[0][0], "Source replication")
drbdtest.ensure('WFBitMapT', evt[0][0], "Target replication")

resource.down()
resource.cluster.teardown()
