#! /usr/bin/env python3
### vmshed: { "vms_all": [3], "vms_ci": [3], "drbd_version_min": "9.0" }

# This test demonstrates that online verify did not terminate when
# the VerifyTarget becomes temporaritly Inconsistent.
# This test makes the VerifyTarget temporaritly Inconsistent by
# triggering a resync towards it.
#
# This bug is present in DRBD up to (including) 9.0.25

from python import drbdtest
from python.drbdtest import connections, log, peer_devices

resource = drbdtest.setup_resource(nodes=3)
resource.disk_options = 'c-max-rate 10M;'
resource.net_options = 'verify-alg md5;'
resource.add_disk('10M')
resource.up_wait()
log('* Make up-to-date data available.')
resource.skip_initial_sync()

node_a, node_b, node_c = resource.nodes
connection_ac = connections(node_a, node_c)
peer_device_bc = peer_devices(node_b, node_c)
peer_device_cb = peer_devices(node_c, node_b)
peer_device_ac = peer_devices(node_a, node_c)

# Make the resync slow, so that the issue triggers
peer_device_ac.peer_device_options("--c-max-rate=250k")
# online verfy should run with 10MByte/sec

log('* Test starts with verify')
peer_device_bc.verify()
peer_device_cb.event(r'peer-device .* replication:VerifyT')
connection_ac.disconnect()
node_a.volumes.write(size='500K', bs='500K')
connection_ac.connect()
peer_device_cb.event(r'peer-device .* replication:Established')
peer_device_bc.event(r'peer-device .* replication:Established', timeout=10)

resource.down()
resource.cluster.teardown()
