#! /usr/bin/env python3
# With more than 3 nodes sometimes the other sync source is chosen.
# Stick to 3 nodes to focus on testing IO and resync endurance.
### vmshed: { "vms_all": [3], "drbd_version_min": "9.2" }

import random
from python import drbdtest, endurance

resource = drbdtest.setup(min_nodes=3)

random.seed()

config = endurance.EnduranceConfig()
# Resync can be very slow when protocol A is used.
# Don't test that until it is fixed in DRBD.
config.protocol = 'C'
config.network_rate = random.choice([None, '300mbit', '1000mbit', '3000mbit', '10000mbit'])
config.disk_delay_ms = random.choice([None, 1, 2, 5, 10])
config.diskless_primary = random.choice([False, True])

drbdtest.log('*** endurance resync config: {}'.format(config))

endurance.run_resync(resource, config)
