[values]
RepositoryURL = ""
RepositoryDistribution = "" # for apt, e.g. bionic
RepositoryPackages = "" # comma separated

[[steps]]
[steps.rsync]
source = "packages/*"
dest = "/opt/packages/"

[[steps]]
[steps.shell]
script = """
PACKAGES=$(printf %s "$REPOSITORY_PACKAGES" | tr , " ")

if command -v yum > /dev/null; then
	if [ -n "$REPOSITORY_URL" ]; then
		cat <<- EOF > /etc/yum.repos.d/drbd.repo
		[drbd]
		name=DRBD Packages
		baseurl=$REPOSITORY_URL
		gpgcheck=0
		enabled=1
		EOF
	fi

	PACKAGES="$PACKAGES $(find /opt/packages -maxdepth 1 -name "*.rpm")"

	no_initramfs=1 yum install -y $PACKAGES

elif command -v apt-get > /dev/null; then
	if [ -n "$REPOSITORY_URL" ]; then
		echo deb [trusted=yes] $REPOSITORY_URL $REPOSITORY_DISTRIBUTION main > /etc/apt/sources.list.d/drbd.list
		apt-get update
	fi

	PACKAGES="$PACKAGES $(find /opt/packages -maxdepth 1 -name "*.deb")"

	DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends $PACKAGES

else
	echo "Unknown package manager"
	exit 1
fi
"""

[steps.shell.env]
REPOSITORY_URL = "{{.RepositoryURL}}"
REPOSITORY_DISTRIBUTION = "{{.RepositoryDistribution}}"
REPOSITORY_PACKAGES = "{{.RepositoryPackages}}"

[[steps]]
[steps.shell]
script = """
mkdir -p /opt/target
cd /opt/target
tar -xzvf /opt/packages/drbd-test-target.tgz
make install
"""
