version = 1

[values]
# KernelPackage is a path to a kernel package file to be installed
KernelPackage = ""
# KernelRelease is the version of the kernel to install from the repositories.
# When neither KernelPackage nor KernelRelease is set, the kernel will not be replaced.
KernelRelease = ""
# KernelRepositoryURL is the URL for the repository containing the kernel package.
KernelRepositoryURL = ""
RepositoryDistribution = "" # for apt, e.g. bionic

# Disable SELinux
[[steps]]
[steps.shell]
script = """
if command -v setenforce > /dev/null; then
	echo "Disabling SELinux"
	setenforce 0
	sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
fi
"""

# Disable any banners from being displayed upon login
[[steps]]
[steps.shell]
script = """
touch /root/.hushlogin
"""

# Configure kernel parameters
[[steps]]
[steps.shell]
script = """
# linbit network routes IPv6 traffic over a slow link, so disable it
echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf
echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf

# log everything to the console
echo 'kernel.printk = 8 8 8 8' >> /etc/sysctl.conf

sysctl -p
"""

# Disable unwanted services
[[steps]]
[steps.shell]
script = """
# Disable unnecessary updates
units="unattended-upgrades.service apt-daily.timer apt-daily-upgrade.timer"

# Disable services which fail anyway
units="$units kdump.service postfix.service fwupd-refresh.service fwupd-refresh.timer"

for u in $units; do
	if systemctl list-unit-files | grep -Fq $u; then
		systemctl disable --now $u
	fi
done
"""

# Uninstall snapd
[[steps]]
[steps.shell]
script = """
if command -v snap > /dev/null; then
	apt-get purge snapd
fi
"""

# Uninstall bcache-tools
[[steps]]
[steps.shell]
script = """
if [ -f /lib/udev/probe-bcache ]; then
	apt-get purge bcache-tools
fi
"""

[[steps]]
[steps.rsync]
source = "{{ .KernelPackage }}"
dest = "/opt/packages-kernel/"

# Install kernel
[[steps]]
[steps.shell]
script = '''
set -e -o pipefail

die() {
	echo -e "$1" >&2
	exit 1
}

mkdir -p /opt/packages-kernel
install_package=$(find /opt/packages-kernel -type f)

[ -z "$KERNEL_RELEASE" -a -z "$install_package" ] && exit 0

# transform "." -> "\." for usage in regexes
kernel_release_regex=${KERNEL_RELEASE//./\\.}

# Install a package from a specific repo, reinstalling if necessary. If the
# package is a file, it will be installed as usual.
rpm_install_repo() {
	local repo="$1"
	local package="$2"
	if [ -e "$package" ] ; then
		yum install -y "$package"
	elif rpm -q "$package" ; then
		yum reinstall -y --disablerepo=* --enablerepo="$repo" "$package"
	else
		yum install -y --disablerepo=* --enablerepo="$repo" "$package"
	fi
}

# usage: <regex>
# assert that there is exactly one kernel installed, and that it maches the specified regex
assert_installed_kernel() {
	local regex="$1"
	local installed_kernels=$(find /boot -maxdepth 1 -name 'vmlinu?-*' -printf "%f\n" | grep -v rescue)
	[ $(echo "$installed_kernels" | wc -l) -eq 1 ] || die "Found != 1 installed kernels:\n$installed_kernels"
	echo "$installed_kernels" | grep -Eq "$regex" || die "Installed kernel does not match expected version: $installed_kernels vs. $regex"
}

kernel::rpm() {
	if yum list kernel-core >/dev/null 2>/dev/null; then
		kernel_prefix=kernel-core
	else
		kernel_prefix=kernel
	fi
	[ -z "$install_package" ] && install_package="${kernel_prefix}-$KERNEL_RELEASE.$(uname -m)"

	if [ -n "$KERNEL_REPOSITORY_URL" ]; then
		cat <<- EOF > /etc/yum.repos.d/kernel.repo
		[drbd-kernel]
		name=Kernel for DRBD Tests
		baseurl=$KERNEL_REPOSITORY_URL
		gpgcheck=0
		enabled=1
		EOF
	fi

	rpm -qa | grep "^${kernel_prefix}-[0-9]\+" | sort > /tmp/had
	rpm_install_repo drbd-kernel "$install_package"
	rpm -qa | grep "^${kernel_prefix}-[0-9]\+" | sort > /tmp/have

	for k in $(comm -12 /tmp/had /tmp/have); do
		[ "$k" = "$install_package" ] && continue

		to_remove=$k
		# On RHEL8 the kernel package is called kernel-core, but we
		# want to remove the kernel metapackage. For AlmaLinux we have
		# to explicitly remove the kernel-core and kernel-modules
		# packages too.
		[ "$kernel_prefix" = "kernel-core" ] && to_remove="${k/kernel-core/kernel} $k ${k/kernel-core/kernel-modules}"

		printf "Removing '%s'\n" "$to_remove"
		# yum autoremove does not like to remove the running kernel
		rpm -e $to_remove
	done

	# also install kernel-modules-extra if available
	if yum list kernel-modules-extra-$KERNEL_RELEASE; then
		rpm_install_repo drbd-kernel "kernel-modules-extra-$KERNEL_RELEASE"
	fi
	assert_installed_kernel "^vmlinuz-${kernel_release_regex}\.x86_64$"
}

# Usage: <regex>
# Searches available packages for a regex, printing the matching package name
deb_regex() {
	apt-cache show "$1" | sed -nr 's/^Package: (.*)$/\1/p'
}

kernel::deb() {
	[ -n "$KERNEL_REPOSITORY_URL" ] && echo deb [trusted=yes] $KERNEL_REPOSITORY_URL $REPOSITORY_DISTRIBUTION main > /etc/apt/sources.list.d/kernel.list
	apt-get update

	[ -z "$install_package" ] && install_package=$(deb_regex "^linux-image-${kernel_release_regex}(-generic)?$")

	# Prevent the newest kernel from being installed automatically
	apt-get autoremove -y linux-virtual linux-image-virtual

	dpkg-query -f '${Package}\n' -W "linux-image-*" | grep 'linux-image-[0-9]\+' | sort > /tmp/had
	apt-get install -y "$install_package"
	dpkg-query -f '${Package}\n' -W "linux-image-*" | grep 'linux-image-[0-9]\+' | sort > /tmp/have

	for k in $(comm -12 /tmp/had /tmp/have); do
		[ "$k" = "$install_package" ] && continue
		apt-get autoremove -y $k linux-image-unsigned-*-generic
	done
	assert_installed_kernel "^vmlinuz-${kernel_release_regex}(-generic)?$"
}

# Set some kernel command line parameters for debugging convenience
sed -i '/GRUB_CMDLINE_LINUX=/s/"\(.*\)"/"\1 nokaslr page_poison=1 crashkernel=no"/' /etc/default/grub

if command -v yum > /dev/null; then
	kernel::rpm
elif command -v apt-get > /dev/null; then
	kernel::deb
else
	echo "Unknown package manager"
	exit 1
fi
rm -f /tmp/ha{d,ve}
'''

[steps.shell.env]
KERNEL_RELEASE = "{{.KernelRelease}}"
KERNEL_REPOSITORY_URL = "{{.KernelRepositoryURL}}"
REPOSITORY_DISTRIBUTION = "{{.RepositoryDistribution}}"
DEBIAN_FRONTEND = "noninteractive"

# Install packages
[[steps]]
[steps.shell]
script = """
set -e
if command -v yum > /dev/null; then
	packages="iptables fio lvm2 make python3 gdisk"
	if ! command -v tc > /dev/null; then
		packages="$packages iproute-tc"
	fi
	yum update -y --exclude=kernel*
	yum install -y $packages
elif command -v apt-get > /dev/null; then
	apt-get update
	apt-get -y upgrade
	apt-get -y install fio thin-provisioning-tools make zfsutils-linux gdisk
else
	echo "Unknown package manager"
	exit 1
fi
"""
[steps.shell.env]
DEBIAN_FRONTEND = "noninteractive"

# Install lbdisttool.py (only for yum)
[[steps]]
[steps.shell]
script = """
if command -v yum > /dev/null; then
	curl -sSLo python-lbdist.tar.gz https://github.com/LINBIT/python-lbdist/archive/master.tar.gz
	tar xvf python-lbdist.tar.gz
	cd python-lbdist-master
	mkdir -p /usr/local/lib/python3.6/site-packages/
	python3 setup.py install
fi
"""
