[values]
RepositoryURL = ""
RepositoryDistribution = "" # for apt, e.g. bionic
RepositoryPackages = "" # comma separated
DrbdVersion = ""

[[steps]]
[steps.rsync]
source = "packages/*"
dest = "/opt/packages/"

[[steps]]
[steps.shell]
script = '''
set -e

die() { >&2 printf "\nError: %s\n" "$*"; exit 1; }

PACKAGES=$(printf %s "$REPOSITORY_PACKAGES" | tr , " ")

if command -v yum > /dev/null; then
	if [ -n "$REPOSITORY_URL" ]; then
		cat <<- EOF > /etc/yum.repos.d/drbd.repo
		[drbd]
		name=DRBD Packages
		baseurl=$REPOSITORY_URL
		gpgcheck=0
		enabled=1
		EOF

		if [ -n "$DRBD_VERSION" ]; then
			AVAILABLE=$(yum list available --quiet --showduplicates \
				--disablerepo="*" --enablerepo="drbd" \
				"kmod-drbd-${DRBD_VERSION}_*" \
					| grep '^kmod-drbd' \
					| awk '{print "kmod-drbd-" $2}')

			echo "Available drbd packages for version $DRBD_VERSION:"
			echo "$AVAILABLE" | tr ' ' '\n'

			BEST=$(lbdisttool.py --kmods $AVAILABLE)
			echo "Best kmod: $BEST"
			PACKAGES="$PACKAGES $BEST"
		fi
	fi

	PACKAGES="$PACKAGES $(find /opt/packages -maxdepth 1 -name "*.rpm")"

	no_initramfs=1 yum install -y $PACKAGES

elif command -v apt-get > /dev/null; then
	if [ -n "$REPOSITORY_URL" ]; then
		echo deb [trusted=yes] $REPOSITORY_URL $REPOSITORY_DISTRIBUTION main > /etc/apt/sources.list.d/drbd.list
		apt-get update

		if [ -n "$DRBD_VERSION" ]; then
			PACKAGES="$PACKAGES drbd-module-$(uname -r)=${DRBD_VERSION}+*"
		fi
	fi

	PACKAGES="$PACKAGES $(find /opt/packages -maxdepth 1 -name "*.deb")"

	DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends $PACKAGES

else
	die "Unknown package manager"
fi

command -v exxe > /dev/null || die "exxe not installed"

echo "Output of 'drbdadm --version':"
drbdadm --version || die "drbd-utils not installed"

modinfo drbd > /dev/null || die "DRBD not installed"
'''

[steps.shell.env]
REPOSITORY_URL = "{{.RepositoryURL}}"
REPOSITORY_DISTRIBUTION = "{{.RepositoryDistribution}}"
REPOSITORY_PACKAGES = "{{.RepositoryPackages}}"
DRBD_VERSION = "{{.DrbdVersion}}"

[[steps]]
[steps.shell]
script = """
mkdir -p /opt/target
cd /opt/target
tar -xzvf /opt/packages/drbd-test-target.tgz
make install
"""
