[values]
RepositoryURL = ""
DrbdRepositoryURL = ""
RepositoryDistribution = "" # for apt, e.g. bionic
RepositoryPackages = "" # comma separated
DrbdVersion = ""

[[steps]]
[steps.rsync]
source = "packages/*"
dest = "/opt/packages/"

[[steps]]
[steps.shell]
script = '''
set -e

die() { >&2 printf "\nError: %s\n" "$*"; exit 1; }

PACKAGES=$(printf %s "$REPOSITORY_PACKAGES" | tr , " ")

[ -z "$DRBD_REPOSITORY_URL" ] && DRBD_REPOSITORY_URL="$REPOSITORY_URL"

if command -v yum > /dev/null; then
	# Cheap hack to allow versions to be specified the same for apt and yum
	PACKAGES=$(printf %s "$PACKAGES" | tr = -)

	if [ -n "$REPOSITORY_URL" ] && [ -n "$DRBD_REPOSITORY_URL" ]; then
		cat <<- EOF > /etc/yum.repos.d/drbd.repo
		[drbd]
		name=DRBD Packages
		baseurl=$DRBD_REPOSITORY_URL
		gpgcheck=0
		enabled=1
		EOF

		if [ "$REPOSITORY_URL" != "$DRBD_REPOSITORY_URL" ]; then
			cat <<- EOF > /etc/yum.repos.d/drbd-extra.repo
			[drbd-extra]
			name=DRBD Extra Packages
			baseurl=$REPOSITORY_URL
			gpgcheck=0
			enabled=1
			EOF
		fi

		if [ -n "$DRBD_VERSION" ]; then
			AVAILABLE=$(yum list available --quiet --showduplicates \
				--disablerepo="*" --enablerepo="drbd" \
				"kmod-drbd-${DRBD_VERSION}_*" \
					| grep '^kmod-drbd' \
					| awk '{print "kmod-drbd-" $2}')

			echo "Available drbd packages for version $DRBD_VERSION:"
			echo "$AVAILABLE" | tr ' ' '\n'

			BEST=$(lbdisttool.py --kmods $AVAILABLE)
			echo "Best kmod: $BEST"
			PACKAGES="$PACKAGES $BEST"
		fi
	fi

	[ -d /opt/packages ] && PACKAGES="$PACKAGES $(find /opt/packages -maxdepth 1 -name "*.rpm")"

	no_initramfs=1 yum install -y $PACKAGES

elif command -v apt-get > /dev/null; then
	if [ -n "$REPOSITORY_URL" ]; then
		echo deb [trusted=yes] $REPOSITORY_URL $REPOSITORY_DISTRIBUTION main > /etc/apt/sources.list.d/drbd.list
		apt-get update

		if [ -n "$DRBD_VERSION" ]; then
			PACKAGES="$PACKAGES drbd-module-$(uname -r)=${DRBD_VERSION}-*"
		fi
	fi

	[ -d /opt/packages ] && PACKAGES="$PACKAGES $(find /opt/packages -maxdepth 1 -name "*.deb")"

	DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends $PACKAGES

else
	die "Unknown package manager"
fi

# For convenience, DRBD can be provided as a module rather than a package
if [ -n "$(find /opt/packages -maxdepth 1 -name '*.ko' -print -quit)" ]; then
	mkdir -p /lib/modules/`uname -r`/updates
	cp -v /opt/packages/*.ko /lib/modules/`uname -r`/updates/
fi

# For convenience, binaries can be provided instead of packages
if [ -n "$(find /opt/packages/bin -maxdepth 1 -type f -print -quit)" ]; then
	cp -v /opt/packages/bin/* /usr/local/bin/
fi

# Just to be sure that drbd can be modprobed
depmod -a

echo "Output of 'drbdadm --version':"
drbdadm --version || die "drbd-utils not installed"

modinfo drbd > /dev/null || die "DRBD not installed"

sed -i 's/usage-count yes/usage-count no/' /etc/drbd.d/global_common.conf

# Include the test resource configs from the standard path for convenience when
# developing tests.
echo 'include "/var/lib/drbd-test/*.res";' > /etc/drbd.d/drbd-test.res
'''

[steps.shell.env]
REPOSITORY_URL = "{{.RepositoryURL}}"
DRBD_REPOSITORY_URL = "{{.DrbdRepositoryURL}}"
REPOSITORY_DISTRIBUTION = "{{.RepositoryDistribution}}"
REPOSITORY_PACKAGES = "{{.RepositoryPackages}}"
DRBD_VERSION = "{{.DrbdVersion}}"
