[values]
ScratchDisk = "/dev/sda"
TestSuiteImage = "drbd9-tests"

[[steps]]
[steps.shell]
script = """
if ! vgs scratch; then
	vgcreate scratch "$SCRATCH_DISK"
fi
"""
[steps.shell.env]
SCRATCH_DISK = "{{.ScratchDisk}}"

[[steps]]
[steps.docker]
image = "{{.TestSuiteImage}}"
