version = 1

[values]
ScratchDisk = "/dev/sda"
TestSuiteImage = "drbd9-tests"
TestsDir = "tests"
RDMA = "" # set to "true" to enable
Storage = "lvm" # Also possible: raw and zfs
OutDir = ""
DrbdVersion = "" # validate that this DRBD version is installed
DrbdVersionOther = ""

[[steps]]
[steps.shell]
script = '''
set -e

# Create RAM disk automatically for convenience.
[ "$SCRATCH_DISK" = "/dev/ram0" -a ! -b "/dev/ram0" ] && modprobe brd rd_nr=1 rd_size=$((10 * 2**20))

# Find the default route which must have a /24 address range.
default_gateway=$(ip route show to 0.0.0.0/0 | awk {'print $3'})
default_route=$(ip route show to match $default_gateway | grep /24)

# Find the device for the default route.
dev=$(printf "%s" "$default_route" | awk '{print $3}')

if [ "$DRBD_TEST_RDMA" = "true" ] ; then
	# Ensure that an RDMA link is available.
	if ! rdma link show | grep ^ ; then
		modprobe rdma_rxe
		echo $dev > /sys/module/rdma_rxe/parameters/add
	fi
fi

# cloud-init configuration with multiple interfaces is tricky, and sometimes they fail.
# Just ignore those services.
systemctl reset-failed "network*.service" || true

while true; do
	running=$(systemctl is-system-running || true)
	[ "$running" = initializing -o "$running" = starting ] && { sleep 1; continue; }
	[ "$running" = running ] && break
	echo "System in unexpected state '$running'; failed units:" 1>&2
	systemctl list-units --failed 1>&2
	exit 1
done
'''
[steps.shell.env]
SCRATCH_DISK = "{{.ScratchDisk}}"
DRBD_TEST_RDMA = "{{.RDMA}}"

[[steps]]
[steps.container]
image = "{{.TestSuiteImage}}"
[steps.container.env]
DRBD_TESTS_DIR = "{{.TestsDir}}"
SCRATCH_DISK = "{{.ScratchDisk}}"
DRBD_TEST_STORAGE = "{{.Storage}}"
DRBD_TEST_RDMA = "{{.RDMA}}"
DRBD_VERSION = "{{.DrbdVersion}}"
DRBD_VERSION_OTHER = "{{.DrbdVersionOther}}"
[steps.container.copy]
source = "/log"
dest = "{{.OutDir}}"

[[steps]]
[steps.shell]
script = '''
# gather gcov output files after a test run.
# loosely based on https://www.kernel.org/doc/html/v6.1/dev-tools/gcov.html

gcov_data=/sys/kernel/debug/gcov
dest=/gcov.tar.gz
tempdir=$(mktemp -d)

[ -d $gcov_data ] || { echo "$gcov_data does not exist, not copying gcov data"; exit 0; }

find $gcov_data -type d -exec mkdir -p $tempdir/\{\} \;
find $gcov_data -name '*.gcda' -exec sh -c 'cat < $0 > '$tempdir'/$0' {} \;
find $gcov_data -name '*.gcno' -exec sh -c 'cp -d $0 '$tempdir'/$0' {} \;
tar czf $dest -C $tempdir sys
rm -rf $tempdir
'''
