test_suite_file = "run.toml"

[[group]]
vms = 2
tests = [
  "add-connect-delete",
  "add-path-multiple-times",
  "connect",
  "fencing",
  "io-errors",
  "resync-initial",
  "promote_while_connecting",
  "verify",
  "resync-finish",
]

[[group]]
vms = 3
tests = [
  "resync-downstream-upstream",
  "outdate",
  "resync-finish2",
]
