test_suite_file = "run.toml"

[[variants]]
name = "tcp"

[[variants]]
name = "rdma"
vm_tags = [ "rdma" ]
variables = { RDMA = "true" }

[tests]
[tests.add-connect-delete]
vms = [2]

[tests.add-path-multiple-times]
vms = [2]

[tests.ahead-behind]
vms = [2]

[tests.allow-remote-read]
vms = [2]

[tests.attach-concurrent]
vms = [3]

[tests.autopromote]
vms = [2]

[tests.busy-resync]
vms = [2]

[tests.c-min-rate]
vms = [2]

[tests.connect]
vms = [2, 5]

[tests.diskless]
vms = [3, 5]
samevms = true

[tests.diskless-join-leave]
vms = [4]

[tests.double-promote-diskless]
vms = [3]

[tests.fencing]
vms = [2, 5]

[tests.force-resync]
vms = [2]

[tests.invalid-names]
vms = [1]

[tests.invalidate]
vms = [2]

[tests.io-errors]
vms = [2]

[tests.io-errors-diskless]
vms = [3]

[tests.may-promote]
vms = [3]

[tests.migrate]
vms = [4]

[tests.misaligned-bio]
vms = [2]

[tests.multi-path]
vms = [2]

[tests.outdate]
vms = [3, 5]

[tests.peer-acks]
vms = [3]

[tests.pre-existing-data]
vms = [3]

[tests.promote_while_connecting]
vms = [2]

[tests.quorum]
vms = [3, 5]

[tests.quorum-failover-reconnect]
vms = [3]

[tests.quorum-isolate-primary]
vms = [3]

[tests.quorum-multi-volume]
vms = [3]

[tests.quorum-suspended-cancel]
vms = [3]

[tests.quorum-suspend-timeout]
vms = [4]

[tests.quorum-tiebreaker]
vms = [3]

[tests.recreate-node-day0]
vms = [3]

[tests.recreate-node-day0-diskless]
vms = [3]

[tests.ref-count]
vms = [2]

[tests.rename]
vms = [1]

[tests.resize]
vms = [2, 5]

[tests.resize-one]
vms = [3]

[tests.resync]
vms = [3]

[tests.resync-after-failover-to-dless]
vms = [3]

[tests.resync-after-primary-crash]
vms = [3]

[tests.resync-based-on-disk-states]
vms = [3]

[tests.resync-between-targets]
vms = [3]

[tests.resync-chain-close]
vms = [3]

[tests.resync-discard]
vms = [2]

[tests.resync-downstream-upstream]
vms = [3]

[tests.resync-finish]
vms = [2]

[tests.resync-finish2]
vms = [3]

[tests.resync-initial]
vms = [2, 5]
samevms = true

[tests.resync-interrupt-variants]
vms = [3]

[tests.resync-multiple-interrupt]
vms = [3]

[tests.resync-reconciliation]
vms = [3]

[tests.resync-source-becomes-target]
vms = [3]

[tests.resync-source-becomes-target2]
vms = [3]

[tests.resync-target-primary]
vms = [3]

[tests.resync-target-promote]
vms = [3]

[tests.resync-target-promote-interrupt]
vms = [3]

[tests.resync-to-older]
vms = [3]

[tests.resync-upstream-downstream]
vms = [3]

[tests.resync-w-dless-pri]
vms = [3]

[tests.revert-older-data]
vms = [2]

[tests.split-brain]
vms = [2]

[tests.stress-al]
vms = [2, 3]

[tests.stress-connect-and-2pc]
vms = [2, 5]

[tests.switch-primaries]
vms = [2, 5]

[tests.switch-sync-source]
vms = [3]

[tests.twopc_abort_connect]
vms = [3]

[tests.two-primaries-reject]
vms = [3]

[tests.unstable-retry]
vms = [4]

[tests.uuid_send_receive_race]
vms = [3]

[tests.verify]
vms = [2]

[tests.verify-target-becomes-inconsistent]
vms = [3]

[tests.write-during-resync]
vms = [3]

