test_suite_file = "run.toml"

[tests]
[tests.add-connect-delete]
vms = [2]

[tests.add-path-multiple-times]
vms = [2]

[tests.allow-remote-read]
vms = [2]

[tests.connect]
vms = [2, 5]

[tests.diskless]
vms = [3, 5]
samevms = true

[tests.diskless-join-leave]
vms = [4]

[tests.double-promote-diskless]
vms = [3]

[tests.fencing]
vms = [2, 5]

[tests.force-resync]
vms = [2]

[tests.io-errors]
vms = [2]

[tests.io-errors-diskless]
vms = [3]

[tests.migrate]
vms = [4]

[tests.misaligned-bio]
vms = [2]

[tests.multi-path]
vms = [2]

[tests.outdate]
vms = [3]

[tests.peer-acks]
vms = [3]

[tests.promote_while_connecting]
vms = [2]

[tests.quorum]
vms = [3]

[tests.quorum-multi-volume]
vms = [3]

[tests.quorum-suspended-cancel]
vms = [3]

[tests.quorum-tiebreaker]
vms = [3]

[tests.ref-count]
vms = [2]

[tests.resize]
vms = [2, 5]

[tests.resync-between-targets]
vms = [3]

[tests.resync-downstream-upstream]
vms = [3]

[tests.resync-finish]
vms = [2]

[tests.resync-initial]
vms = [2]
samevms = true

[tests.resync-target-primary]
vms = [3]

[tests.resync-target-promote]
vms = [3]

[tests.resync-to-older]
vms = [3]

[tests.resync-upstream-downstream]
vms = [3]

[tests.split-brain]
vms = [2]

[tests.stress-al]
vms = [2, 3]

[tests.stress-connect-and-2pc]
vms = [2]

[tests.switch-primaries]
vms = [2, 5]

[tests.twopc_abort_connect]
vms = [3]

[tests.verify]
vms = [2]

[tests.verify-target-becomes-inconsistent]
vms = [3]

[tests.write-during-resync]
vms = [3]
