[[variants]]
name = "tcp"

[[variants]]
name = "rdma"
vm_tags = [ "rdma" ]
variables = { RDMA = "true" }

[[variants]]
name = "raw"
variables = { Storage = "raw" }

[[variants]]
name = "zfs"
vm_tags = [ "zfs" ]
variables = { Storage = "zfs" }
