[[variants]]
name = "tcp"
vm_tags = [ "distro" ]

[[variants]]
name = "tls"
vm_tags = [ "tls" ]
variables = { TLS = "yes" }

[[variants]]
name = "rdma"
vm_tags = [ "rdma", "distro" ]
variables = { Transport = "rdma" }

[[variants]]
name = "raw"
vm_tags = [ "distro" ]
variables = { Storage = "raw" }

[[variants]]
name = "zfs"
vm_tags = [ "zfs", "distro" ]
variables = { Storage = "zfs" }

# For compatibility testing - install the "other" version on the second node
[[variants]]
name = "second_is_other"
vm_tags = [ "distro" ]
variables = { DrbdOtherNode = "1" }

[[variants]]
name = "mainline"
vm_tags = [ "mainline" ]
