# This is appended to the base image name to form the test image name
name = "t"
provision_file = "provision-test.toml"

[[vms]]
base_image = "alma-8-drbd-k348"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/rhel8/"

[vms.metadata]
BuildDistribution = "rhel8.5"
KernelRelease = "4.18.0-348.el8"
SourceImage = "alma-8"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel8/"


[[vms]]
base_image = "alma-8-drbd-k305"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/rhel8/"

[vms.metadata]
BuildDistribution = "rhel8.4"
KernelRelease = "4.18.0-305.el8"
SourceImage = "alma-8"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel8/"


[[vms]]
base_image = "alma-8-drbd-k147"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/rhel8/"

[vms.metadata]
BuildDistribution = "rhel8.1"
KernelRelease = "4.18.0-147.el8"
SourceImage = "alma-8"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel8/"


[[vms]]
base_image = "centos-7-drbd-k1160"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/rhel7/"

[vms.metadata]
BuildDistribution = "rhel7.9"
KernelRelease = "3.10.0-1160.el7"
SourceImage = "centos-7"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel7/"


[[vms]]
base_image = "centos-7-drbd-k862"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/rhel7/"

[vms.metadata]
BuildDistribution = "rhel7.5"
KernelRelease = "3.10.0-862.el7"
SourceImage = "centos-7"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel7/"


[[vms]]
base_image = "centos-7-drbd-k229"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/rhel7/"

[vms.metadata]
BuildDistribution = "rhel7.1"
KernelRelease = "3.10.0-229.1.2.el7"
SourceImage = "centos-7"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel7/"


[[vms]]
base_image = "ubuntu-xenial-drbd-k210"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-xenial/"
RepositoryDistribution = "xenial"

[vms.metadata]
BuildDistribution = "ubuntu-xenial"
KernelRelease = "4.4.0-210"
SourceImage = "ubuntu-xenial"


[[vms]]
base_image = "ubuntu-bionic-drbd-k159"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-bionic/"
RepositoryDistribution = "bionic"

[vms.metadata]
BuildDistribution = "ubuntu-bionic"
KernelRelease = "4.15.0-159"
SourceImage = "ubuntu-bionic"


[[vms]]
base_image = "ubuntu-focal-drbd-k88"
vcpus = 1
memory = "1G"

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-focal/"
RepositoryDistribution = "focal"

[vms.metadata]
BuildDistribution = "ubuntu-focal"
KernelRelease = "5.4.0-88"
SourceImage = "ubuntu-focal"
