# This is appended to the base image name to form the test image name
name = "t"
provision_file = "provision-test.toml"

[[vms]]
base_image = "rhel-9-drbd-k362"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module not available
vm_tags = [ "discard-stat", "distro", "tls", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel9/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel9.3/drbd-9/$basearch/"
RhelSecretsURL = "https://nexus.at.linbit.com/repository/lbbuild/rhel-secrets/secrets-x86_64.tar.gz"
ReleaseVer = "9.3"

[vms.metadata]
BuildDistribution = "rhel9.3"
BuildKernel = "5.14.0-362.8.1.el9_3"
KernelRelease = "5.14.0-362.8.1.el9_3"
SourceImage = "rhel:9.3"


[[vms]]
base_image = "rhel-9-drbd-k70"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module not available
vm_tags = [ "discard-stat", "distro", "tls", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel9/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel9.0/drbd-9/$basearch/"
RhelSecretsURL = "https://nexus.at.linbit.com/repository/lbbuild/rhel-secrets/secrets-x86_64.tar.gz"
ReleaseVer = "9.0"

[vms.metadata]
BuildDistribution = "rhel9.0"
BuildKernel = "5.14.0-70.13.1.el9_0"
KernelRelease = "5.14.0-70.13.1.el9_0"
SourceImage = "rhel:9.0"


[[vms]]
base_image = "rhel-8-drbd-k477"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module prints:
# Warning: Soft-RoCE Transport Driver - This driver has not undergone sufficient testing by Red Hat for this release and therefore cannot be used in production systems.
vm_tags = [ "discard-stat", "distro", "tls", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel8/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel8.8/drbd-9/$basearch/"
RhelSecretsURL = "https://nexus.at.linbit.com/repository/lbbuild/rhel-secrets/secrets-x86_64.tar.gz"
ReleaseVer = "8.8"

[vms.metadata]
BuildDistribution = "rhel8.8"
BuildKernel = "4.18.0-477.10.1.el8_8"
KernelRelease = "4.18.0-477.10.1.el8_8"
SourceImage = "rhel:8.8"


[[vms]]
base_image = "rhel-8-drbd-k147"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
vm_tags = [ "discard-stat", "rdma", "distro", "tls", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel8/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel8.1/drbd-9/$basearch/"
RhelSecretsURL = "https://nexus.at.linbit.com/repository/lbbuild/rhel-secrets/secrets-x86_64.tar.gz"
ReleaseVer = "8.1"

[vms.metadata]
BuildDistribution = "rhel8.1"
BuildKernel = "4.18.0-147.el8"
KernelRelease = "4.18.0-147.8.1.el8_1"
SourceImage = "rhel:8.1"


[[vms]]
base_image = "rhel-7-drbd-k1160"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
vm_tags = [ "rdma", "distro", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel7/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel7.9/drbd-9/$basearch/"
RhelSecretsURL = "https://nexus.at.linbit.com/repository/lbbuild/rhel-secrets/7/secrets-x86_64.tar.gz"
ReleaseVer = "7.9"

[vms.metadata]
BuildDistribution = "rhel7.9"
BuildKernel = "3.10.0-1160.el7"
KernelRelease = "3.10.0-1160.49.1.el7"
SourceImage = "rhel:7.9"


[[vms]]
base_image = "ubuntu-bionic-drbd-k213"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module not installed.
vm_tags = [ "zfs", "distro", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-bionic/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "bionic"

[vms.metadata]
BuildDistribution = "ubuntu-bionic"
BuildKernel = "4.15.0-213"
KernelRelease = "4.15.0-213"
SourceImage = "ubuntu-bionic"


[[vms]]
base_image = "ubuntu-focal-drbd-k190"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module not installed.
vm_tags = [ "discard-stat", "zfs", "distro", "tls", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-focal/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "focal"

[vms.metadata]
BuildDistribution = "ubuntu-focal"
BuildKernel = "5.4.0-190-generic"
KernelRelease = "5.4.0-190-generic"
SourceImage = "ubuntu-focal"


[[vms]]
base_image = "ubuntu-jammy-drbd-k117"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module not installed.
vm_tags = [ "discard-stat", "zfs", "dm-ebs", "distro", "tls", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-jammy/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "jammy"

[vms.metadata]
BuildDistribution = "ubuntu-jammy"
BuildKernel = "5.15.0-117-generic"
KernelRelease = "5.15.0-117-generic"
SourceImage = "ubuntu-jammy"


[[vms]]
base_image = "ubuntu-noble-drbd-k39"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module is part of linux-modules-extra which is not installed.
vm_tags = [ "discard-stat", "zfs", "dm-ebs", "distro", "tls", "raw" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-noble/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "noble"

[vms.metadata]
BuildDistribution = "ubuntu-noble"
BuildKernel = "6.8.0-39-generic"
KernelRelease = "6.8.0-39-generic"
SourceImage = "ubuntu-noble"


[[vms]]
base_image = "mainline-drbd-k6.9.0"
vcpus = 2
memory = "1G"
disks = ["name=data,size=1G,bus=scsi,format=qcow2,pool=scratch"]
# No RDMA support. rdma_rxe module not installed.
# No ZFS support in upstream Linux
vm_tags = [ "discard-stat", "dm-ebs", "mainline", "tls", "raw" ]

[vms.values]
DrbdRepositoryURL = "https://nexus.at.linbit.com/repository/mainline/"
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-jammy/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "jammy"

[vms.metadata]
BuildDistribution = "mainline"
BuildKernel = "6.9.0-linbit"
KernelRelease = "6.9.0-linbit"
SourceImage = "ubuntu-jammy"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/mainline-kernels/"
