# This is appended to the base image name to form the test image name
name = "t"
provision_file = "provision-test.toml"

[[vms]]
base_image = "alma-9-drbd-k70"
vcpus = 2
memory = "1G"
# No RDMA support. rdma_rxe module not available
vm_tags = [ "discard-stat", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel9/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel9.0/drbd-9/$basearch/"

[vms.metadata]
BuildDistribution = "rhel9.0"
BuildKernel = "5.14.0-70.13.1.el9_0" # kernel from RHEL9-rc1 for now, change when final is released
KernelRelease = "5.14.0-70.13.1.el9_0"
SourceImage = "alma-9"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel9/"


[[vms]]
base_image = "alma-8-drbd-k348"
vcpus = 2
memory = "1G"
# No RDMA support. rdma_rxe module prints:
# Warning: Soft-RoCE Transport Driver - This driver has not undergone sufficient testing by Red Hat for this release and therefore cannot be used in production systems.
vm_tags = [ "discard-stat", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel8/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel8.5/drbd-9/$basearch/"

[vms.metadata]
BuildDistribution = "rhel8.5"
BuildKernel = "4.18.0-348.el8"
KernelRelease = "4.18.0-348.2.1.el8_5"
SourceImage = "alma-8"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel8/"


[[vms]]
base_image = "alma-8-drbd-k305"
vcpus = 2
memory = "1G"
# No RDMA support. Connection frequently fails with "repost of tx_desc failed! -104".
vm_tags = [ "discard-stat", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel8/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel8.4/drbd-9/$basearch/"

[vms.metadata]
BuildDistribution = "rhel8.4"
BuildKernel = "4.18.0-305.el8"
KernelRelease = "4.18.0-305.25.1.el8_4"
SourceImage = "alma-8"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel8/"


[[vms]]
base_image = "alma-8-drbd-k147"
vcpus = 2
memory = "1G"
vm_tags = [ "discard-stat", "rdma", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel8/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel8.1/drbd-9/$basearch/"

[vms.metadata]
BuildDistribution = "rhel8.1"
BuildKernel = "4.18.0-147.el8"
KernelRelease = "4.18.0-147.8.1.el8_1"
SourceImage = "alma-8"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel8/"


[[vms]]
base_image = "centos-7-drbd-k1160"
vcpus = 2
memory = "1G"
vm_tags = [ "rdma", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel7/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel7/drbd-9/$basearch/"

[vms.metadata]
BuildDistribution = "rhel7.9"
BuildKernel = "3.10.0-1160.el7"
KernelRelease = "3.10.0-1160.49.1.el7"
SourceImage = "centos-7"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel7/"


[[vms]]
base_image = "centos-7-drbd-k862"
vcpus = 2
memory = "1G"
vm_tags = [ "rdma", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ci-yum/rhel7/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/yum/rhel7/drbd-9/$basearch/"

[vms.metadata]
BuildDistribution = "rhel7.5"
BuildKernel = "3.10.0-862.el7"
KernelRelease = "3.10.0-862.14.4.el7"
SourceImage = "centos-7"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/rhel-kernels/rhel7/"


[[vms]]
base_image = "ubuntu-bionic-drbd-k210"
vcpus = 2
memory = "1G"
# No RDMA support. rdma_rxe module not installed.
vm_tags = [ "zfs", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-bionic/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "bionic"

[vms.metadata]
BuildDistribution = "ubuntu-bionic"
BuildKernel = "4.15.0-210"
KernelRelease = "4.15.0-210"
SourceImage = "ubuntu-bionic"


[[vms]]
base_image = "ubuntu-focal-drbd-k148"
vcpus = 2
memory = "1G"
# No RDMA support. rdma_rxe module not installed.
vm_tags = [ "discard-stat", "zfs", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-focal/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "focal"

[vms.metadata]
BuildDistribution = "ubuntu-focal"
BuildKernel = "5.4.0-148"
KernelRelease = "5.4.0-148"
SourceImage = "ubuntu-focal"


[[vms]]
base_image = "ubuntu-jammy-drbd-k69"
vcpus = 2
memory = "1G"
# No RDMA support. rdma_rxe module not installed.
vm_tags = [ "discard-stat", "zfs", "dm-ebs", "distro" ]

[vms.values]
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-jammy/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "jammy"

[vms.metadata]
BuildDistribution = "ubuntu-jammy"
BuildKernel = "5.15.0-69"
KernelRelease = "5.15.0-69"
SourceImage = "ubuntu-jammy"

[[vms]]
base_image = "mainline-drbd-k6.3.0"
vcpus = 2
memory = "1G"
# No RDMA support. rdma_rxe module not installed.
# No ZFS support in upstream Linux
vm_tags = [ "discard-stat", "dm-ebs", "mainline" ]

[vms.values]
DrbdRepositoryURL = "https://nexus.at.linbit.com/repository/mainline/"
RepositoryURL = "https://nexus.at.linbit.com/repository/ubuntu-jammy/"
ReleaseRepositoryURL = "https://nexus.at.linbit.com/repository/packages-linbit-com/"
RepositoryDistribution = "jammy"

[vms.metadata]
BuildDistribution = "mainline"
BuildKernel = "6.3.0-linbit"
KernelRelease = "6.3.0-linbit"
SourceImage = "ubuntu-jammy"
KernelRepositoryURL = "https://nexus.at.linbit.com/repository/mainline-kernels/"
